[project]
name = "street"
description = ""
authors = []
telemetry = false
cache_dir = "./.cache"

[[project.requirements]]
contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard"

# [contracts.counter]
# path = "contracts/counter.clar"
# epoch = "latest"

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More information: https://www.hiro.so/blog/new-safety-checks-in-clarinet

# [repl.analysis]
# passes = []
# passes = ["check_checker"]
# check_checker = { trusted_sender = true, trusted_caller = true, callee_filter = false, strict = false }

[repl.analysis.lints]

[contracts]

[contracts.credit-controller]
path = "contracts/credit-controller.clar"
clarity_version = 4
epoch = "latest"

[contracts.credit-token]
path = "contracts/credit-token.clar"
clarity_version = 4
epoch = "latest"

[contracts.emission-controller]
path = "contracts/emission-controller.clar"
clarity_version = 4
epoch = "latest"

[contracts.street-controller]
path = "contracts/street-controller.clar"
clarity_version = 4
epoch = "latest"

[contracts.street-market]
path = "contracts/street-market.clar"
clarity_version = 4
epoch = "latest"

[contracts.street-nft]
path = "contracts/street-nft.clar"
clarity_version = 4
epoch = "latest"

[contracts.street-rewards]
path = "contracts/street-rewards.clar"
clarity_version = 4
epoch = "latest"

[contracts.street-token]
path = "contracts/street-token.clar"
clarity_version = 4
epoch = "latest"

[contracts.welsh-faucet]
path = "contracts/welsh-faucet.clar"
clarity_version = 4
epoch = "latest"

[contracts.welshcorgicoin]
path = "contracts/welshcorgicoin.clar"
clarity_version = 4
epoch = "latest"
